from alpine

ARG tutorial_path=/tutorials/CHT/heat_exchanger/buoyantSimpleFoam-CalculiX
RUN apk add git bash
ARG branch=develop
RUN git clone --branch $branch https://github.com/precice/tutorials

# Copy modified configs
COPY controlDict $tutorial_path/Inner-Fluid/system/controlDict
COPY controlDict $tutorial_path/Outer-Fluid/system/controlDict

# Download meshes
WORKDIR $tutorial_path
RUN bash ./Download_meshes && \
    cp -r Inner-Fluid/constant/polyMesh.org Inner-Fluid/constant/polyMesh && \
    cp -r Outer-Fluid/constant/polyMesh.org Outer-Fluid/constant/polyMesh

WORKDIR /
RUN mkdir configs
RUN sed -i 's|exchange-directory\="."|exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g; \
            s|max-time value=".*"|max-time value="1"|g; \
            s|\(\s\+\)\(</participant>\)|\1  <export:vtk directory="precice-output" />\n\1\2|g' \
            $tutorial_path/precice-config.xml && \
            cat $tutorial_path/precice-config.xml && \
            cp $tutorial_path/precice-config.xml configs/ && \
            cp $tutorial_path/config.yml configs/
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
