ARG branch=develop
ARG from=precice/precice-ubuntu1804.home-${branch}
FROM $from

ARG CACHEBUST

USER precice
WORKDIR /home/precice
RUN git clone https://github.com/dealii/dealii.git && \
    mkdir dealii_build && \
    cd dealii_build && \
    cmake \
    -D DEAL_II_WITH_UMFPACK="ON" \
    -D DEAL_II_WITH_THREADS="ON" \
    -D DEAL_II_COMPONENT_EXAMPLES="OFF" \
    ../dealii && \
    make -j $(nproc)
