ARG from=precice/precice-ubuntu1604.home-develop
ARG base_solver=precice/deal.ii
FROM ${base_solver} as deal.ii
FROM $from

COPY --from=deal.ii /root/dealii/ /home/precice/dealii/

USER precice
WORKDIR /home/precice
RUN git clone https://github.com/precice/dealii-adapter.git
RUN cd dealii-adapter && \
    cmake -DDEAL_II_DIR=$HOME/dealii -DCMAKE_BUILD_TYPE=Release . && \
    make -j $(nproc) 

RUN mkdir -p Data/Input Data/Output Data/Exchange
WORKDIR /home/precice/dealii-adapter
