from alpine
ENV tutorial_path tutorials/FSI/flap_perp/SU2-CalculiX
RUN apk add git bash
ARG branch=develop
RUN git clone --branch $branch https://github.com/precice/tutorials

RUN mkdir configs && \
    sed -e 's|exchange-directory="\.\./"|exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g; s|max-iterations value="50"|max-iterations value="25"|g'\
    $tutorial_path/precice-config.xml  > configs/precice-config.xml
RUN rm $tutorial_path/precice-config.xml
RUN cp $tutorial_path/config.yml configs/
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
