from alpine

RUN apk add git
ARG branch=develop

WORKDIR /
# adjust configuration and paths
RUN mkdir /Output
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice /Output
USER precice
