from alpine

ENV tutorial_path /tutorials/CHT/flow-over-plate/buoyantPimpleFoam-nutils
RUN apk add git
ARG branch=develop
RUN git clone --depth 1 --branch $branch https://github.com/precice/tutorials

WORKDIR /
# adjust configuration and paths
RUN  mkdir configs && cp $tutorial_path/precice-config.xml configs/precice-config.xml && \
     sed -i 's|exchange-directory="\.\."|exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g; \
             s|\(\s\+\)\(</participant>\)|\1   <export:vtk directory="precice-output" />\n\1\2|g' \
             configs/precice-config.xml && \
     sed -i 's|\.\./precice-config\.xml|configs/precice-config.xml|g' $tutorial_path/Nutils/cht.py && \
     sed -i 's|\.\./precice-config\.xml|configs/precice-config.xml|g' $tutorial_path/OpenFOAM/system/preciceDict
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
