from alpine
ENV tutorial_path tutorials/FSI/flap_perp_2D/OpenFOAM-deal.II
RUN apk add git

ARG branch=develop
RUN git clone --depth 1  --branch $branch https://github.com/precice/tutorials
RUN mkdir configs && \
    sed -e 's|m2n:sockets from="Fluid" to="Solid"|m2n:sockets from="Fluid" to="Solid" exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g; \
    s|max-time value="5"|max-time value="1"|g ; \
    s|\(\s\+\)\(</participant>\)|\1   <export:vtk directory="precice-output" />\n\1\2|g' \
 		$tutorial_path/precice-config.xml > configs/precice-config.xml

# When running on older OF versions (<= 5.x, <= v1712), perform substitution below
# RUN sed -i '/application     pimpleFoam/d; s/\/\/ application     pimpleDyMFoam/application    pimpleDyMFoam/g' $tutorial_path/Fluid/system/controlDict

RUN rm $tutorial_path/precice-config.xml
RUN rm -rfv $tutorial_path/Fluid/0/
RUN cp -r $tutorial_path/Fluid/0.orig/ $tutorial_path/Fluid/0/
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
