from alpine
ENV tutorial_path tutorials/HT/partitioned-heat/fenics-fenics
RUN apk add git
ARG branch=develop
RUN git clone --branch $branch https://github.com/precice/tutorials
RUN mkdir configs && sed -i 's|network="lo"|exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g' $tutorial_path/precice-config.xml

RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
