ARG from=precice/precice-ubuntu1804.home-develop
FROM $from
USER root

RUN apt-get -qq update && apt-get -qq install \
    liblapack-dev && \
    rm -rf /var/lib/apt/lists/*


ARG CACHEBUST


USER precice

WORKDIR /home/precice/
ARG branch=develop
RUN git clone --depth 1 --branch $branch https://github.com/precice/elastictube1d.git

WORKDIR /home/precice/elastictube1d/cxx

RUN sed -i 's|\(\s\+\)\(</participant>\)|\1   <export:vtk directory="precice-output" />\n\1\2|g' \
            precice-config.xml
RUN cmake . && make all
