ARG from=precice/precice-ubuntu1804.home-develop
FROM $from
USER root

RUN apt-get -qq update && apt-get -qq install \
    liblapack-dev && \
    rm -rf /var/lib/apt/lists/*


ARG CACHEBUST


USER precice

WORKDIR /home/precice/
ARG branch=develop
RUN git clone --branch $branch https://github.com/precice/elastictube1d.git

RUN mkdir -p Data/Output/Postproc
WORKDIR /home/precice/elastictube1d/cxx
RUN cmake . && make all
