from alpine
ENV tutorial_path tutorials/partitioned-heat-conduction
RUN apk add git
ARG branch=develop
RUN git clone --depth 1 --branch $branch https://github.com/precice/tutorials
RUN mkdir configs && \
    sed -i 's|<m2n:sockets from="HeatDirichlet" to="HeatNeumann"/>|<m2n:sockets from="HeatDirichlet" to="HeatNeumann" exchange-directory="/home/precice/Data/Exchange/" network="eth0"/>|g; \
            s|\(\s\+\)\(</participant>\)|\1   <export:vtk directory="precice-output" />\n\1\2|g' $tutorial_path/precice-config.xml

RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
