from alpine

ENV tutorial_path /tutorials/CHT/flow-over-plate/buoyantSimpleFoam-aster
ENV ca_adapter_path /home/precice/code_aster-adapter/cht
RUN apk add git bash

    # Change this branch to 'develop'
ARG branch=CA_OpenFOAM
RUN git clone --branch $branch https://github.com/precice/tutorials

COPY \
    docker.export $tutorial_path/Solid/solid.export

RUN \
    cd $tutorial_path/Solid $$ mkdir REPE_OUT \
    && echo "F comm $ca_adapter_path/adapter.comm D 1" >> solid.export \
    && echo "F libr $tutorial_path/config.comm D 90" >> solid.export \
    && echo "F libr $tutorial_path/Solid/def.comm" >> solid.export \
    && echo "F mmed $tutorial_path/Solid/solid.mmed D 20" >> solid.export \
    && echo "R repe $tutorial_path/Solid/REPE_OUT D 0" >> solid.export \
    && echo "R mmed $tutorial_path/Solid/REPE_OUT R 0" >> solid.export \
    && echo "F mess $tutorial_path/Solid/solid.mess R 6" >> solid.export \
    && echo "F rmed $tutorial_path/Solid/solid.rmed R 80" >> solid.export \
    && echo "F resu $tutorial_path/Solid/solid.resu R 8" >> solid.export


# RUN cd $tutorial_path && ./Allrun
