from alpine
ENV tutorial_path tutorials/FSI/flap_perp/SU2-CalculiX
RUN apk add git bash
ARG branch=develop
RUN git clone --branch $branch https://github.com/precice/tutorials

RUN mkdir configs && \
    sed -e 's|m2n:sockets from="SU2_CFD" to="Calculix" |m2n:sockets from="SU2_CFD" to="Calculix" exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g; \
            s|max-time-windows value="400"|max-time-windows value="50"|g; s|max-iterations value="50"|max-iterations value="20"|g; \
            s|\(\s\+\)\(</participant>\)|\1   <export:vtk directory="precice-output" />\n\1\2|g' \
            $tutorial_path/precice-config.xml  > configs/precice-config.xml

RUN rm $tutorial_path/precice-config.xml
RUN cp $tutorial_path/config.yml configs/
RUN cp $tutorial_path/runFluid configs/ && cp $tutorial_path/runSolid configs/
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
