from alpine
ENV tutorial_path tutorials/FSI/flap_perp/OpenFOAM-deal.II
RUN apk add git

RUN git clone https://github.com/precice/tutorials
RUN mkdir configs && sed -e 's|gather-scatter"|gather-scatter" exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g' $tutorial_path/precice-config_serial.xml > configs/precice-config.xml
RUN sed -i '/application     pimpleFoam/d; s/\/\/ application     pimpleDyMFoam/application    pimpleDyMFoam/g' \
    $tutorial_path/Fluid/system/controlDict
RUN rm $tutorial_path/precice-config_serial.xml $tutorial_path/precice-config.xml
RUN rm -rfv $tutorial_path/Fluid/0/
RUN cp -r $tutorial_path/Fluid/0.orig/ $tutorial_path/Fluid/0/
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
