from alpine

ENV tutorial_path /tutorials/{{tutorial_path}}
RUN apk add git bash
RUN git clone https://github.com/precice/tutorials

# NOTE: Adjust your configuration here and copy precice config to configs/precice-config.xml

# TODO: Adjust regex
WORKDIR /
RUN sed -i 's|exchange-directory\="."|exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g' \
    configs/precice-config.xml && cp $tutorial_path/config.yml  configs/config.yml
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
