from alpine

ENV tutorial_path /tutorials/{{tutorial_path}}
RUN apk add git bash
RUN git clone https://github.com/precice/tutorials

# NOTE: Adjust your configuration here and copy precice config to configs/precice-config.xml

# NOTE: Regex below might need adjustment depending on the structure of your precice-config. The
# appended commands should remain the same (exchange-directory and network). If you use different
# precice-config different from the tutorial, make sure to adjust in the similar way
WORKDIR /
RUN sed -i 's|exchange-directory\="."|exchange-directory="/home/precice/Data/Exchange/" network="eth0"|g' \
    configs/precice-config.xml && cp $tutorial_path/config.yml  configs/config.yml
RUN addgroup -g 1000 precice && adduser -u 1000 -G precice -D precice && chown -R precice:precice tutorials configs
USER precice
